BLACK = ( 0, 0, 0)
WHITE = (255, 255, 255)
GREEN = (0, 255, 0)
RED = ( 255, 0, 0)

FRAME_RATE = 10

TYPE_TEXT = "TEXT"
TYPE_ANIMATED_TEXT = "ANIMATED_TEXT"

RESOURCES_LOCATION = "resources"
RESOURCES_FONTS_LOCATION = "fonts"
RESOURCES_SCRIPTS_LOCATION = "videoscripts"
OUTPUT_FRAMES_LOCATION = "frames"
OUTPUT_LOCATION = "output"
OUTPUT_VIDEO_LOCATION = "video"
